// @ts-check

/**
 * Extension builtin and keyword additions.
 *
 * @typedef {object} ExtensionEntry
 * @property {string[]} [typeNames] Built-in type-like names introduced by the extension.
 * @property {string[]} [variableNames] Built-in variable names introduced by the extension.
 * @property {string[]} [constantNames] Built-in constant names introduced by the extension.
 * @property {string[]} [functionNames] Built-in function names introduced by the extension.
 * @property {Record<string, 'variable.builtin' | 'constant.builtin' | 'function.builtin' | 'type.builtin'>} [definedMacros] Macro aliases defined by the extension, keyed by name with highlight capture role as value.
 * @property {string[]} [typeKeywords] Type keywords added to the grammar by the extension.
 * @property {string[]} [storageQualifiers] Storage qualifier keywords added by the extension.
 * @property {string[]} [precisionQualifiers] Precision qualifier keywords added by the extension.
 * @property {string[]} [interpolationQualifiers] Interpolation qualifier keywords added by the extension.
 * @property {string[]} [attributes] Attribute keywords added by the extension.
 * @property {string[]} [includes] Other extension keys whose identifiers are included by this extension.
 * @property {Record<string, (($: any) => any)>} [grammarExtension] Tree-sitter rule builders to merge into the grammar.
 *
 * Extension-owned builtin and keyword additions keyed by extension name.
 * @typedef {{[extension: string]: ExtensionEntry}} ExtensionRegistry
 *
 * Unified extension registry shared by builtin and keyword registries.
 * @type {ExtensionRegistry}
 */
const EXTENSIONS = {
  GL_AMD_shader_explicit_vertex_parameter: {
    typeNames: ['__explicitInterpAMD'],
    variableNames: [
      'gl_BaryCoordNoPerspAMD',
      'gl_BaryCoordNoPerspCentroidAMD',
      'gl_BaryCoordNoPerspSampleAMD',
      'gl_BaryCoordPullModelAMD',
      'gl_BaryCoordSmoothAMD',
      'gl_BaryCoordSmoothCentroidAMD',
      'gl_BaryCoordSmoothSampleAMD',
    ],
    functionNames: ['interpolateAtVertexAMD'],
  },
  GL_AMD_shader_fragment_mask: {
    functionNames: ['fragmentFetchAMD', 'fragmentMaskFetchAMD'],
  },
  GL_ARB_shader_stencil_export: {variableNames: ['gl_FragStencilRefARB']},
  GL_ARM_cooperative_matrix_layouts: {
    constantNames: [
      'gl_CooperativeMatrixLayoutColumnBlockedInterleavedARM',
      'gl_CooperativeMatrixLayoutRowBlockedInterleavedARM',
    ],
  },
  GLSL_ARM_shader_core_builtins: {
    variableNames: [
      'gl_CoreCountARM',
      'gl_CoreIDARM',
      'gl_CoreMaxIDARM',
      'gl_WarpIDARM',
      'gl_WarpMaxIDARM',
    ],
  },
  GL_ARM_tensors: {
    typeNames: ['tensorARM'],
    constantNames: [
      'gl_TensorOperandsNonTemporalARM',
      'gl_TensorOperandsOutOfBoundsValueARM',
    ],
    functionNames: ['tensorReadARM', 'tensorSizeARM', 'tensorWriteARM'],
    typeKeywords: ['tensorARM'],
  },
  GL_EXT_bfloat16: {
    functionNames: [
      'bfloat16BitsToIntEXT',
      'bfloat16BitsToUintEXT',
      'intBitsToBFloat16EXT',
      'uintBitsToBFloat16EXT',
    ],
    typeKeywords: ['bfloat16_t', 'bf16vec2', 'bf16vec3', 'bf16vec4'],
  },
  GLSL_EXT_buffer_reference: {attributes: ['buffer_reference']},
  GLSL_EXT_buffer_reference2: {attributes: ['buffer_reference_align']},
  GLSL_EXT_buffer_reference_uvec2: {},
  GL_EXT_control_flow_attributes: {
    attributes: [
      'unroll',
      'dont_unroll',
      'loop',
      'dependency_infinite',
      'dependency_length',
      'flatten',
      'dont_flatten',
      'branch',
    ],
  },
  GL_EXT_control_flow_attributes2: {
    attributes: [
      'min_iterations',
      'max_iterations',
      'iteration_multiple',
      'peel_count',
      'partial_count',
    ],
  },
  GLSL_EXT_debug_printf: {functionNames: ['debugPrintfEXT']},
  GLSL_EXT_demote_to_helper_invocation: {
    grammarExtension: {
      // Spec: demote_statement : DEMOTE (spec omits semicolon but
      // real usage always includes it, consistent with discard)
      // Injection: simple_statement
      demote_statement: (_) => seq('demote', ';'),
    },
    functionNames: ['helperInvocationEXT'],
  },
  GLSL_EXT_descriptor_heap: {
    typeNames: ['nonuniformEXT'],
    attributes: ['descriptor_heap', 'descriptor_stride'],
  },
  GL_EXT_device_group: {variableNames: ['gl_DeviceIndex']},
  GL_EXT_expect_assume: {functionNames: ['assumeEXT', 'expectEXT']},
  GL_EXT_float_e4m3: {
    functionNames: [
      'floate4m3BitsToIntEXT',
      'floate4m3BitsToUintEXT',
      'intBitsToFloate4m3EXT',
      'saturatedConvertEXT',
      'uintBitsToFloate4m3EXT',
    ],
    typeKeywords: ['floate4m3_t', 'fe4m3vec2', 'fe4m3vec3', 'fe4m3vec4'],
  },
  GL_EXT_float_e5m2: {
    functionNames: [
      'floate5m2BitsToIntEXT',
      'floate5m2BitsToUintEXT',
      'intBitsToFloate5m2EXT',
      'saturatedConvertEXT',
      'uintBitsToFloate5m2EXT',
    ],
    typeKeywords: ['floate5m2_t', 'fe5m2vec2', 'fe5m2vec3', 'fe5m2vec4'],
  },
  GLSL_EXT_fragment_invocation_density: {
    variableNames: ['gl_FragInvocationCountEXT', 'gl_FragSizeEXT'],
  },
  GLSL_EXT_fragment_shader_barycentric: {
    typeNames: ['pervertexEXT'],
    variableNames: ['gl_BaryCoordEXT', 'gl_BaryCoordNoPerspEXT'],
    storageQualifiers: ['pervertexEXT'],
  },
  GLSL_EXT_fragment_shading_rate: {
    variableNames: ['gl_PrimitiveShadingRateEXT', 'gl_ShadingRateEXT'],
    constantNames: [
      'gl_ShadingRateFlag2HorizontalPixelsEXT',
      'gl_ShadingRateFlag2VerticalPixelsEXT',
      'gl_ShadingRateFlag4HorizontalPixelsEXT',
      'gl_ShadingRateFlag4VerticalPixelsEXT',
    ],
  },
  GLSL_EXT_integer_dot_product: {
    functionNames: [
      'dotAccSatEXT',
      'dotEXT',
      'dotPacked4x8AccSatEXT',
      'dotPacked4x8EXT',
    ],
  },
  GLSL_EXT_long_vector: {},
  GL_EXT_maximal_reconvergence: {attributes: ['maximally_reconverges']},
  GLSL_EXT_mesh_shader: {
    typeNames: [
      'gl_MeshPerPrimitiveEXT',
      'gl_MeshPerVertexEXT',
      'perprimitiveEXT',
      'taskPayloadSharedEXT',
    ],
    variableNames: [
      'gl_ClipDistancePerViewEXT',
      'gl_CullDistancePerViewEXT',
      'gl_CullPrimitiveEXT',
      'gl_MeshPrimitivesEXT',
      'gl_MeshVerticesEXT',
      'gl_PrimitiveLineIndicesEXT',
      'gl_PrimitivePointIndicesEXT',
      'gl_PrimitiveShadingRateEXT',
      'gl_PrimitiveTriangleIndicesEXT',
    ],
    functionNames: ['EmitMeshTasksEXT', 'SetMeshOutputsEXT'],
    storageQualifiers: ['perprimitiveEXT', 'taskPayloadSharedEXT'],
  },
  GL_EXT_multiview: {variableNames: ['gl_ViewIndex']},
  GLSL_EXT_nontemporal_keyword: {storageQualifiers: ['nontemporal']},
  GL_EXT_nonuniform_qualifier: {
    typeNames: ['nonuniformEXT'],
    storageQualifiers: ['nonuniformEXT'],
  },
  GL_EXT_null_initializer: {},
  GLSL_EXT_opacity_micromap: {
    constantNames: ['gl_RayFlagsForceOpacityMicromap2StateEXT'],
  },
  GLSL_EXT_ray_cull_mask: {variableNames: ['gl_CullMaskEXT']},
  GLSL_EXT_ray_flags_primitive_culling: {
    constantNames: ['gl_RayFlagsSkipAABBEXT', 'gl_RayFlagsSkipTrianglesEXT'],
    attributes: ['primitive_culling'],
  },
  GLSL_EXT_ray_query: {
    typeNames: ['accelerationStructureEXT', 'rayQueryEXT'],
    constantNames: [
      'gl_RayFlagsCullBackFacingTrianglesEXT',
      'gl_RayFlagsCullFrontFacingTrianglesEXT',
      'gl_RayFlagsCullNoOpaqueEXT',
      'gl_RayFlagsCullOpaqueEXT',
      'gl_RayFlagsNoOpaqueEXT',
      'gl_RayFlagsNoneEXT',
      'gl_RayFlagsOpaqueEXT',
      'gl_RayFlagsSkipClosestHitShaderEXT',
      'gl_RayFlagsTerminateOnFirstHitEXT',
      'gl_RayQueryCandidateIntersectionAABBEXT',
      'gl_RayQueryCandidateIntersectionTriangleEXT',
      'gl_RayQueryCommittedIntersectionGeneratedEXT',
      'gl_RayQueryCommittedIntersectionNoneEXT',
      'gl_RayQueryCommittedIntersectionTriangleEXT',
    ],
    functionNames: [
      'rayQueryConfirmIntersectionEXT',
      'rayQueryGenerateIntersectionEXT',
      'rayQueryGetIntersectionBarycentricsEXT',
      'rayQueryGetIntersectionCandidateAABBOpaqueEXT',
      'rayQueryGetIntersectionFrontFaceEXT',
      'rayQueryGetIntersectionGeometryIndexEXT',
      'rayQueryGetIntersectionInstanceCustomIndexEXT',
      'rayQueryGetIntersectionInstanceIdEXT',
      'rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT',
      'rayQueryGetIntersectionObjectRayDirectionEXT',
      'rayQueryGetIntersectionObjectRayOriginEXT',
      'rayQueryGetIntersectionObjectToWorldEXT',
      'rayQueryGetIntersectionPrimitiveIndexEXT',
      'rayQueryGetIntersectionTEXT',
      'rayQueryGetIntersectionTypeEXT',
      'rayQueryGetIntersectionWorldToObjectEXT',
      'rayQueryGetRayFlagsEXT',
      'rayQueryGetRayTMinEXT',
      'rayQueryGetWorldRayDirectionEXT',
      'rayQueryGetWorldRayOriginEXT',
      'rayQueryInitializeEXT',
      'rayQueryProceedEXT',
      'rayQueryTerminateEXT',
    ],
    typeKeywords: ['accelerationStructureEXT', 'rayQueryEXT'],
  },
  GLSL_EXT_ray_tracing: {
    typeNames: [
      'accelerationStructureEXT',
      'callableDataEXT',
      'callableDataInEXT',
      'hitAttributeEXT',
      'rayPayloadEXT',
      'rayPayloadInEXT',
      'shaderRecordEXT',
    ],
    variableNames: [
      'gl_GeometryIndexEXT',
      'gl_HitKindEXT',
      'gl_HitTEXT',
      'gl_IncomingRayFlagsEXT',
      'gl_InstanceCustomIndexEXT',
      'gl_LaunchIDEXT',
      'gl_LaunchSizeEXT',
      'gl_ObjectRayDirectionEXT',
      'gl_ObjectRayOriginEXT',
      'gl_ObjectToWorldEXT',
      'gl_RayTmaxEXT',
      'gl_RayTminEXT',
      'gl_WorldRayDirectionEXT',
      'gl_WorldRayOriginEXT',
      'gl_WorldToObjectEXT',
    ],
    constantNames: [
      'gl_HitKindBackFacingTriangleEXT',
      'gl_HitKindFrontFacingTriangleEXT',
      'gl_RayFlagsCullBackFacingTrianglesEXT',
      'gl_RayFlagsCullFrontFacingTrianglesEXT',
      'gl_RayFlagsCullNoOpaqueEXT',
      'gl_RayFlagsCullOpaqueEXT',
      'gl_RayFlagsNoOpaqueEXT',
      'gl_RayFlagsNoneEXT',
      'gl_RayFlagsOpaqueEXT',
      'gl_RayFlagsSkipClosestHitShaderEXT',
      'gl_RayFlagsTerminateOnFirstHitEXT',
      'gl_ScopeShaderCallEXT',
    ],
    functionNames: [
      'executeCallableEXT',
      'ignoreIntersectionEXT',
      'reportIntersectionEXT',
      'terminateRayEXT',
      'traceRayEXT',
    ],
    definedMacros: {
      gl_ObjectToWorld3x4EXT: 'variable.builtin',
      gl_WorldToObject3x4EXT: 'variable.builtin',
    },
    typeKeywords: ['accelerationStructureEXT'],
    storageQualifiers: [
      'callableDataEXT',
      'callableDataInEXT',
      'hitAttributeEXT',
      'rayPayloadEXT',
      'rayPayloadInEXT',
      'shadercallcoherent',
      'shaderRecordEXT',
    ],
  },
  GLSL_EXT_ray_tracing_position_fetch: {
    variableNames: ['gl_HitTriangleVertexPositionsEXT'],
    functionNames: ['rayQueryGetIntersectionTriangleVertexPositionsEXT'],
  },
  GL_EXT_samplerless_texture_functions: {},
  GL_EXT_scalar_block_layout: {attributes: ['scalar']},
  GL_EXT_shader_16bit_storage: {},
  GL_EXT_shader_64bit_indexing: {functionNames: ['length64']},
  GLSL_EXT_shader_atomic_float: {
    functionNames: [
      'atomicLoad',
      'atomicStore',
      'imageAtomicLoad',
      'imageAtomicStore',
    ],
  },
  GLSL_EXT_shader_atomic_float2: {
    functionNames: ['atomicLoad', 'atomicStore'],
  },
  GL_EXT_shader_atomic_int64: {},
  GL_EXT_shader_explicit_arithmetic_types: {
    typeKeywords: [
      'float64_t',
      'f64vec2',
      'f64vec3',
      'f64vec4',
      'f64mat2',
      'f64mat3',
      'f64mat4',
      'f64mat2x2',
      'f64mat2x3',
      'f64mat2x4',
      'f64mat3x2',
      'f64mat3x3',
      'f64mat3x4',
      'f64mat4x2',
      'f64mat4x3',
      'f64mat4x4',
      'float32_t',
      'f32vec2',
      'f32vec3',
      'f32vec4',
      'f32mat2',
      'f32mat3',
      'f32mat4',
      'f32mat2x2',
      'f32mat2x3',
      'f32mat2x4',
      'f32mat3x2',
      'f32mat3x3',
      'f32mat3x4',
      'f32mat4x2',
      'f32mat4x3',
      'f32mat4x4',
      'float16_t',
      'f16vec2',
      'f16vec3',
      'f16vec4',
      'f16mat2',
      'f16mat3',
      'f16mat4',
      'f16mat2x2',
      'f16mat2x3',
      'f16mat2x4',
      'f16mat3x2',
      'f16mat3x3',
      'f16mat3x4',
      'f16mat4x2',
      'f16mat4x3',
      'f16mat4x4',
      'int64_t',
      'i64vec2',
      'i64vec3',
      'i64vec4',
      'uint64_t',
      'u64vec2',
      'u64vec3',
      'u64vec4',
      'int32_t',
      'i32vec2',
      'i32vec3',
      'i32vec4',
      'uint32_t',
      'u32vec2',
      'u32vec3',
      'u32vec4',
      'int16_t',
      'i16vec2',
      'i16vec3',
      'i16vec4',
      'uint16_t',
      'u16vec2',
      'u16vec3',
      'u16vec4',
      'int8_t',
      'i8vec2',
      'i8vec3',
      'i8vec4',
      'uint8_t',
      'u8vec2',
      'u8vec3',
      'u8vec4',
    ],
    functionNames: [
      'pack64',
      'pack32',
      'pack16',
      'unpack32',
      'unpack16',
      'unpack8',
      'packInt2x32',
      'packUint2x32',
      'unpackInt2x32',
      'unpackUint2x32',
      'packFloat2x16',
      'unpackFloat2x16',
      'packInt2x16',
      'packInt4x16',
      'packUint2x16',
      'packUint4x16',
      'unpackInt2x16',
      'unpackInt4x16',
      'unpackUint2x16',
      'unpackUint4x16',
      'halfBitsToInt16',
      'halfBitsToUint16',
      'int16BitsToHalf',
      'uint16BitsToHalf',
      'doubleBitsToInt64',
      'doubleBitsToUint64',
      'int64BitsToDouble',
      'uint64BitsToDouble',
      'float16BitsToInt16',
      'float16BitsToUint16',
      'int16BitsToFloat16',
      'uint16BitsToFloat16',
    ],
  },
  GLSL_EXT_shader_image_int64: {},
  GLSL_EXT_shader_invocation_reorder: {
    typeNames: ['hitObjectEXT'],
    variableNames: [
      'gl_HitKindEXT',
      'gl_LaunchIDEXT',
      'gl_RayFlagsEXT',
      'gl_RayTMaxEXT',
      'gl_RayTMinEXT',
    ],
    functionNames: [
      'hitObjectExecuteShaderEXT',
      'hitObjectGetAttributesEXT',
      'hitObjectGetCurrentTimeEXT',
      'hitObjectGetGeometryIndexEXT',
      'hitObjectGetHitKindEXT',
      'hitObjectGetInstanceCustomIndexEXT',
      'hitObjectGetInstanceIdEXT',
      'hitObjectGetIntersectionTriangleVertexPositionsEXT',
      'hitObjectGetObjectRayDirectionEXT',
      'hitObjectGetObjectRayOriginEXT',
      'hitObjectGetObjectToWorldEXT',
      'hitObjectGetPrimitiveIndexEXT',
      'hitObjectGetRayFlagsEXT',
      'hitObjectGetRayTMaxEXT',
      'hitObjectGetRayTMinEXT',
      'hitObjectGetShaderBindingTableRecordIndexEXT',
      'hitObjectGetShaderRecordBufferHandleEXT',
      'hitObjectGetWorldRayDirectionEXT',
      'hitObjectGetWorldRayOriginEXT',
      'hitObjectGetWorldToObjectEXT',
      'hitObjectIsEmptyEXT',
      'hitObjectIsHitEXT',
      'hitObjectIsMissEXT',
      'hitObjectRecordEmptyEXT',
      'hitObjectRecordFromQueryEXT',
      'hitObjectRecordMissEXT',
      'hitObjectRecordMissMotionEXT',
      'hitObjectReorderExecuteEXT',
      'hitObjectSetShaderBindingTableRecordIndexEXT',
      'hitObjectTraceMotionReorderExecuteEXT',
      'hitObjectTraceRayEXT',
      'hitObjectTraceRayMotionEXT',
      'hitObjectTraceReorderExecuteEXT',
      'reorderThreadEXT',
    ],
    typeKeywords: ['hitObjectEXT'],
    storageQualifiers: ['hitObjectAttributeEXT'],
    attributes: ['hitobjectshaderrecordext'],
  },
  GLSL_EXT_shader_quad_control: {},
  GL_EXT_shader_realtime_clock: {
    functionNames: ['clockRealtime2x32EXT', 'clockRealtimeEXT'],
  },
  GL_EXT_shader_subgroup_extended_types_float16: {},
  GL_EXT_shader_subgroup_extended_types_int16: {},
  GL_EXT_shader_subgroup_extended_types_int64: {},
  GL_EXT_shader_subgroup_extended_types_int8: {},
  GLSL_EXT_shader_tile_image: {
    typeNames: ['attachmentEXT', 'iattachmentEXT', 'uattachmentEXT'],
    functionNames: [
      'colorAttachmentReadEXT',
      'depthAttachmentReadEXT',
      'stencilAttachmentReadEXT',
    ],
    typeKeywords: ['attachmentEXT', 'iattachmentEXT', 'uattachmentEXT'],
    storageQualifiers: ['tileImageEXT'],
    attributes: [
      'non_coherent_color_attachment_readEXT',
      'non_coherent_depth_attachment_readEXT',
      'non_coherent_stencil_attachment_readEXT',
    ],
  },
  GL_EXT_shared_memory_block: {},
  GLSL_EXT_spec_constant_composites: {},
  GLSL_EXT_spirv_intrinsics: {},
  GL_EXT_subgroup_uniform_control_flow: {
    attributes: ['subgroup_uniform_control_flow'],
  },
  GL_EXT_subgroupuniform_qualifier: {
    typeNames: ['subgroupuniformEXT'],
    storageQualifiers: ['subgroupuniformEXT'],
  },
  GL_EXT_terminate_invocation: {
    grammarExtension: {
      terminate_invocation_statement: (_) => seq('terminateInvocation', ';'),
    },
  },
  GL_EXT_texture_offset_non_const: {},
  GLSL_EXT_uniform_buffer_unsized_array: {},
  GL_EXT_vulkan_glsl_relaxed: {},
  GLSL_HUAWEI_cluster_culling_shader: {
    typeNames: ['gl_PerClusterHUAWEI'],
    variableNames: [
      'gl_ClusterIDHUAWEI',
      'gl_FirstIndexHUAWEI',
      'gl_FirstInstanceHUAWEI',
      'gl_FirstVertexHUAWEI',
      'gl_IndexCountHUAWEI',
      'gl_InstanceCountHUAWEI',
      'gl_VertexCountHUAWEI',
      'gl_VertexOffsetHUAWEI',
    ],
  },
  GLSL_HUAWEI_subpass_shading: {},
  GLSL_KHR_cooperative_matrix: {
    typeKeywords: ['coopmat'],
    constantNames: [
      'gl_CooperativeMatrixLayoutRowMajor',
      'gl_CooperativeMatrixLayoutColumnMajor',
      'gl_MatrixUseA',
      'gl_MatrixUseB',
      'gl_MatrixUseAccumulator',
      'gl_MatrixOperandsSaturatingAccumulation',
    ],
    functionNames: ['coopMatLoad', 'coopMatStore', 'coopMatMulAdd'],
  },
  GL_KHR_memory_scope_semantics: {
    constantNames: [
      'gl_ScopeDevice',
      'gl_ScopeWorkgroup',
      'gl_ScopeSubgroup',
      'gl_ScopeInvocation',
      'gl_ScopeQueueFamily',
      'gl_SemanticsRelaxed',
      'gl_SemanticsAcquire',
      'gl_SemanticsRelease',
      'gl_SemanticsAcquireRelease',
      'gl_SemanticsMakeAvailable',
      'gl_SemanticsMakeVisible',
      'gl_SemanticsVolatile',
      'gl_StorageSemanticsNone',
      'gl_StorageSemanticsBuffer',
      'gl_StorageSemanticsShared',
      'gl_StorageSemanticsImage',
      'gl_StorageSemanticsOutput',
    ],
    functionNames: [
      'atomicLoad',
      'atomicStore',
      'controlBarrier',
      'imageAtomicLoad',
      'imageAtomicStore',
    ],
  },
  GL_KHR_shader_subgroup: {
    variableNames: [
      'gl_NumSubgroups',
      'gl_SubgroupID',
      'gl_SubgroupSize',
      'gl_SubgroupInvocationID',
      'gl_SubgroupEqMask',
      'gl_SubgroupGeMask',
      'gl_SubgroupGtMask',
      'gl_SubgroupLeMask',
      'gl_SubgroupLtMask',
    ],
    functionNames: [
      'subgroupBarrier',
      'subgroupMemoryBarrier',
      'subgroupMemoryBarrierBuffer',
      'subgroupMemoryBarrierShared',
      'subgroupMemoryBarrierImage',
      'subgroupElect',
      'subgroupAll',
      'subgroupAny',
      'subgroupAllEqual',
      'subgroupBroadcast',
      'subgroupBroadcastFirst',
      'subgroupBallot',
      'subgroupInverseBallot',
      'subgroupBallotBitExtract',
      'subgroupBallotBitCount',
      'subgroupBallotInclusiveBitCount',
      'subgroupBallotExclusiveBitCount',
      'subgroupBallotFindLSB',
      'subgroupBallotFindMSB',
      'subgroupShuffle',
      'subgroupShuffleXor',
      'subgroupShuffleUp',
      'subgroupShuffleDown',
      'subgroupAdd',
      'subgroupMul',
      'subgroupMin',
      'subgroupMax',
      'subgroupAnd',
      'subgroupOr',
      'subgroupXor',
      'subgroupInclusiveAdd',
      'subgroupInclusiveMul',
      'subgroupInclusiveMin',
      'subgroupInclusiveMax',
      'subgroupInclusiveAnd',
      'subgroupInclusiveOr',
      'subgroupInclusiveXor',
      'subgroupExclusiveAdd',
      'subgroupExclusiveMul',
      'subgroupExclusiveMin',
      'subgroupExclusiveMax',
      'subgroupExclusiveAnd',
      'subgroupExclusiveOr',
      'subgroupExclusiveXor',
      'subgroupClusteredAdd',
      'subgroupClusteredMul',
      'subgroupClusteredMin',
      'subgroupClusteredMax',
      'subgroupClusteredAnd',
      'subgroupClusteredOr',
      'subgroupClusteredXor',
      'subgroupQuadBroadcast',
      'subgroupQuadSwapHorizontal',
      'subgroupQuadSwapVertical',
      'subgroupQuadSwapDiagonal',
    ],
  },
  GL_KHR_shader_subgroup_rotate: {
    functionNames: ['subgroupRotate', 'subgroupClusteredRotate'],
  },
  GL_KHR_vulkan_glsl: {
    attributes: [
      'push_constant',
      'constant_id',
      'input_attachment_index',
      'local_size_x_id',
      'local_size_y_id',
      'local_size_z_id',
      'set',
    ],
    constantNames: ['gl_MaxInputAttachments'],
  },
  GL_NVX_multiview_per_view_attributes: {
    variableNames: ['gl_PositionPerViewNV', 'gl_ViewportMaskPerViewNV'],
  },
  GLSL_NV_cluster_acceleration_structure: {
    variableNames: ['gl_ClusterIDNV'],
    constantNames: ['gl_ClusterIDNoneNV'],
    functionNames: [
      'hitObjectGetClusterIdNV',
      'rayQueryGetIntersectionClusterIdNV',
    ],
  },
  GLSL_NV_compute_shader_derivatives: {
    typeNames: ['derivative_group_linearNV', 'derivative_group_quadsNV'],
    attributes: ['derivative_group_linearNV', 'derivative_group_quadsNV'],
  },
  GLSL_NV_cooperative_matrix: {
    typeNames: ['coopmatNV', 'fcoopmatNV', 'icoopmatNV', 'ucoopmatNV'],
    functionNames: ['coopMatLoadNV', 'coopMatMulAddNV', 'coopMatStoreNV'],
    typeKeywords: ['coopmatNV', 'fcoopmatNV', 'icoopmatNV', 'ucoopmatNV'],
  },
  GLSL_NV_cooperative_matrix2: {
    typeNames: ['tensorLayoutNV', 'tensorViewNV'],
    constantNames: [
      'gl_CooperativeMatrixClampModeClampToEdgeNV',
      'gl_CooperativeMatrixClampModeConstantNV',
      'gl_CooperativeMatrixClampModeMirrorRepeatNV',
      'gl_CooperativeMatrixClampModeRepeatNV',
      'gl_CooperativeMatrixClampModeUndefinedNV',
      'gl_CooperativeMatrixReduce2x2NV',
      'gl_CooperativeMatrixReduceColumnNV',
      'gl_CooperativeMatrixReduceRowAndColumnNV',
      'gl_CooperativeMatrixReduceRowNV',
    ],
    functionNames: [
      'coopMatLoadTensorNV',
      'coopMatPerElementNV',
      'coopMatReduceNV',
      'coopMatStoreTensorNV',
      'coopMatTransposeNV',
      'createTensorLayoutNV',
      'createTensorViewNV',
      'setTensorLayoutBlockSizeNV',
      'setTensorLayoutClampValueNV',
      'setTensorLayoutDimensionNV',
      'setTensorLayoutStrideNV',
      'setTensorViewClipNV',
      'setTensorViewDimensionsNV',
      'setTensorViewStrideNV',
      'sliceTensorLayoutNV',
    ],
    typeKeywords: ['tensorLayoutNV', 'tensorViewNV'],
  },
  GLSL_NV_cooperative_vector: {
    typeNames: ['coopvecNV'],
    constantNames: [
      'gl_ComponentTypeFloat16NV',
      'gl_ComponentTypeFloat32NV',
      'gl_ComponentTypeFloat64NV',
      'gl_ComponentTypeFloatE4M3NV',
      'gl_ComponentTypeFloatE5M2NV',
      'gl_ComponentTypeSignedInt16NV',
      'gl_ComponentTypeSignedInt32NV',
      'gl_ComponentTypeSignedInt64NV',
      'gl_ComponentTypeSignedInt8NV',
      'gl_ComponentTypeSignedInt8PackedNV',
      'gl_ComponentTypeUnsignedInt16NV',
      'gl_ComponentTypeUnsignedInt32NV',
      'gl_ComponentTypeUnsignedInt64NV',
      'gl_ComponentTypeUnsignedInt8NV',
      'gl_ComponentTypeUnsignedInt8PackedNV',
      'gl_CooperativeVectorMatrixLayoutColumnMajorNV',
      'gl_CooperativeVectorMatrixLayoutInferencingOptimalNV',
      'gl_CooperativeVectorMatrixLayoutRowMajorNV',
      'gl_CooperativeVectorMatrixLayoutTrainingOptimalNV',
    ],
    functionNames: [
      'coopVecLoadNV',
      'coopVecMatMulAddNV',
      'coopVecMatMulNV',
      'coopVecOuterProductAccumulateNV',
      'coopVecReduceSumAccumulateNV',
      'coopVecStoreNV',
    ],
    typeKeywords: ['coopvecNV'],
  },
  GLSL_NV_displacement_micromap: {
    variableNames: [
      'gl_HitKindBackFacingMicroTriangleNV',
      'gl_HitKindFrontFacingMicroTriangleNV',
      'gl_HitMicroTriangleVertexBarycentricsNV',
      'gl_HitMicroTriangleVertexPositionsNV',
    ],
    functionNames: [
      'fetchMicroTriangleVertexBarycentricNV',
      'fetchMicroTriangleVertexPositionNV',
    ],
  },
  GLSL_NV_explicit_typecast: {},
  GLSL_NV_fragment_shader_barycentric: {
    typeNames: ['pervertexNV'],
    variableNames: ['gl_BaryCoordNV', 'gl_BaryCoordNoPerspNV'],
    storageQualifiers: ['pervertexNV'],
  },
  GLSL_NV_linear_swept_spheres: {
    variableNames: [
      'gl_HitIsLSSNV',
      'gl_HitIsSphereNV',
      'gl_HitKindNV',
      'gl_HitLSSPositionsNV',
      'gl_HitLSSRadiiNV',
      'gl_HitSpherePositionNV',
      'gl_HitSphereRadiusNV',
    ],
    constantNames: ['gl_RayFlagsSkipBuiltinPrimitivesNV'],
    functionNames: [
      'hitObjectGetLSSPositionsNV',
      'hitObjectGetLSSRadiiNV',
      'hitObjectGetSpherePositionNV',
      'hitObjectGetSphereRadiusNV',
      'rayQueryGetIntersectionLSSHitValueNV',
      'rayQueryGetIntersectionLSSPositionsNV',
      'rayQueryGetIntersectionLSSRadiiNV',
      'rayQueryGetIntersectionSpherePositionNV',
      'rayQueryGetIntersectionSphereRadiusNV',
      'rayQueryIsLSSHitNV',
      'rayQueryIsSphereHitNV',
    ],
  },
  GLSL_NV_mesh_shader: {
    typeNames: ['gl_MeshPerPrimitiveNV', 'gl_MeshPerVertexNV'],
    variableNames: [
      'gl_ClipDistancePerViewNV',
      'gl_CullDistancePerViewNV',
      'gl_LayerPerViewNV',
      'gl_MeshPrimitivesNV',
      'gl_MeshVerticesNV',
      'gl_MeshViewCountNV',
      'gl_MeshViewIndicesNV',
      'gl_PositionPerViewNV',
      'gl_PrimitiveCountNV',
      'gl_PrimitiveIndicesNV',
      'gl_TaskCountNV',
      'gl_ViewportMaskPerViewNV',
    ],
    constantNames: ['gl_MaxMeshViewCountNV'],
    functionNames: ['writePackedPrimitiveIndices4x8NV'],
    storageQualifiers: ['perprimitiveNV', 'perviewNV', 'taskNV'],
  },
  GLSL_NV_primitive_shading_rate: {
    variableNames: [
      'gl_FragmentSizeNV',
      'gl_InvocationsPerPixelNV',
      'gl_ShadingRateNV',
      'gl_ShadingRatePerViewNV',
    ],
  },
  GLSL_NV_push_constant_bank: {attributes: ['bank', 'member_offset']},
  GLSL_NV_ray_tracing: {
    typeNames: [
      'accelerationStructureNV',
      'shaderRecordNV',
      'subgroupPartitionNV',
    ],
    variableNames: [
      'gl_HitKindNV',
      'gl_HitTNV',
      'gl_IncomingRayFlagsNV',
      'gl_InstanceCustomIndexNV',
      'gl_LaunchIDNV',
      'gl_LaunchSizeNV',
      'gl_ObjectRayDirectionNV',
      'gl_ObjectRayOriginNV',
      'gl_ObjectToWorldNV',
      'gl_RayTmaxNV',
      'gl_RayTminNV',
      'gl_WorldRayDirectionNV',
      'gl_WorldRayOriginNV',
      'gl_WorldToObjectNV',
    ],
    constantNames: [
      'gl_RayFlagsCullBackFacingTrianglesNV',
      'gl_RayFlagsCullFrontFacingTrianglesNV',
      'gl_RayFlagsCullNoOpaqueNV',
      'gl_RayFlagsCullOpaqueNV',
      'gl_RayFlagsNoOpaqueNV',
      'gl_RayFlagsNoneNV',
      'gl_RayFlagsOpaqueNV',
      'gl_RayFlagsSkipClosestHitShaderNV',
      'gl_RayFlagsTerminateOnFirstHitNV',
    ],
    functionNames: [
      'executeCallableNV',
      'ignoreIntersectionNV',
      'reportIntersectionNV',
      'terminateRayNV',
      'traceNV',
    ],
    typeKeywords: ['accelerationStructureNV'],
    storageQualifiers: [
      'callableDataInNV',
      'callableDataNV',
      'hitAttributeNV',
      'rayPayloadInNV',
      'rayPayloadNV',
      'shaderRecordNV',
    ],
  },
  GLSL_NV_ray_tracing_motion_blur: {
    variableNames: ['gl_CurrentRayTimeNV'],
    functionNames: ['traceRayMotionNV'],
  },
  GLSL_NV_shader_invocation_reorder: {
    typeNames: ['hitObjectNV'],
    functionNames: [
      'hitObjectExecuteShaderNV',
      'hitObjectGetAttributesNV',
      'hitObjectGetCurrentTimeNV',
      'hitObjectGetGeometryIndexNV',
      'hitObjectGetHitKindNV',
      'hitObjectGetInstanceCustomIndexNV',
      'hitObjectGetInstanceIdNV',
      'hitObjectGetObjectRayDirectionNV',
      'hitObjectGetObjectRayOriginNV',
      'hitObjectGetObjectToWorldNV',
      'hitObjectGetPrimitiveIndexNV',
      'hitObjectGetRayTMaxNV',
      'hitObjectGetRayTMinNV',
      'hitObjectGetShaderBindingTableRecordIndexNV',
      'hitObjectGetShaderRecordBufferHandleNV',
      'hitObjectGetWorldRayDirectionNV',
      'hitObjectGetWorldRayOriginNV',
      'hitObjectGetWorldToObjectNV',
      'hitObjectIsEmptyNV',
      'hitObjectIsHitNV',
      'hitObjectIsMissNV',
      'hitObjectRecordEmptyNV',
      'hitObjectRecordHitMotionNV',
      'hitObjectRecordHitNV',
      'hitObjectRecordHitWithIndexMotionNV',
      'hitObjectRecordHitWithIndexNV',
      'hitObjectRecordMissMotionNV',
      'hitObjectRecordMissNV',
      'hitObjectTraceRayMotionNV',
      'hitObjectTraceRayNV',
      'reorderThreadNV',
    ],
    typeKeywords: ['hitObjectNV'],
    storageQualifiers: ['hitObjectAttributeNV'],
    attributes: ['hitobjectshaderrecordnv'],
  },
  GLSL_NV_shader_sm_builtins: {
    variableNames: [
      'gl_HelperThreadNV',
      'gl_SMCountNV',
      'gl_SMIDNV',
      'gl_ThreadInWarpNV',
      'gl_WarpIDNV',
      'gl_WarpSizeNV',
      'gl_WarpsPerSMNV',
    ],
    functionNames: [
      'activeThreadsNV',
      'ballotThreadNV',
      'quadSwizzle0NV',
      'quadSwizzle1NV',
      'quadSwizzle2NV',
      'quadSwizzle3NV',
      'quadSwizzleXNV',
      'quadSwizzleYNV',
    ],
  },
  GL_NV_shader_subgroup_partitioned: {
    functionNames: [
      'subgroupPartitionNV',
      'subgroupPartitionedAddNV',
      'subgroupPartitionedAndNV',
      'subgroupPartitionedExclusiveAddNV',
      'subgroupPartitionedExclusiveAndNV',
      'subgroupPartitionedExclusiveMaxNV',
      'subgroupPartitionedExclusiveMinNV',
      'subgroupPartitionedExclusiveMulNV',
      'subgroupPartitionedExclusiveOrNV',
      'subgroupPartitionedExclusiveXorNV',
      'subgroupPartitionedInclusiveAddNV',
      'subgroupPartitionedInclusiveAndNV',
      'subgroupPartitionedInclusiveMaxNV',
      'subgroupPartitionedInclusiveMinNV',
      'subgroupPartitionedInclusiveMulNV',
      'subgroupPartitionedInclusiveOrNV',
      'subgroupPartitionedInclusiveXorNV',
      'subgroupPartitionedMaxNV',
      'subgroupPartitionedMinNV',
      'subgroupPartitionedMulNV',
      'subgroupPartitionedOrNV',
      'subgroupPartitionedXorNV',
    ],
  },
  GLSL_NV_shader_texture_footprint: {
    typeNames: ['gl_TextureFootprint2DNV', 'gl_TextureFootprint3DNV'],
    functionNames: [
      'textureFootprintClampNV',
      'textureFootprintGradClampNV',
      'textureFootprintGradNV',
      'textureFootprintLodNV',
      'textureFootprintNV',
    ],
  },
  GLSL_NV_shading_rate_image: {
    variableNames: [
      'gl_FragSizeNV',
      'gl_FragmentSizeNV',
      'gl_InvocationsPerPixelNV',
    ],
  },
  GLSL_QCOM_cooperative_matrix_conversion: {
    functionNames: [
      'bitcastQCOM',
      'coopmatToVectorQCOM',
      'extractSubArrayQCOM',
      'vectorToCoopmatQCOM',
    ],
  },
  GLSL_QCOM_image_processing: {
    functionNames: [
      'textureBlockMatchSADQCOM',
      'textureBlockMatchSSDQCOM',
      'textureBoxFilterQCOM',
      'textureWeightedQCOM',
    ],
  },
  GLSL_QCOM_image_processing2: {
    functionNames: [
      'textureBlockMatchGatherSADQCOM',
      'textureBlockMatchGatherSSDQCOM',
      'textureBlockMatchWindowSADQCOM',
      'textureBlockMatchWindowSSDQCOM',
    ],
  },
  GLSL_QCOM_tile_shading: {
    typeNames: [
      'non_coherent_attachment_readQCOM',
      'shading_rate_xQCOM',
      'shading_rate_yQCOM',
      'shading_rate_zQCOM',
      'tile_attachmentQCOM',
    ],
    variableNames: [
      'gl_TileApronSizeQCOM',
      'gl_TileDimensionQCOM',
      'gl_TileOffsetQCOM',
    ],
  },
  GL_AMD_shader_trinary_minmax: {functionNames: ['max3', 'mid3', 'min3']},
  GLSL_EXT_shader_subgroup_extended_types: {
    includes: [
      'GL_EXT_shader_subgroup_extended_types_float16',
      'GL_EXT_shader_subgroup_extended_types_int16',
      'GL_EXT_shader_subgroup_extended_types_int64',
      'GL_EXT_shader_subgroup_extended_types_int8',
    ],
  },
};

/**
 * Resolves `includes` references on each extension entry, merging the
 * referenced entries' identifiers into the including entry.  The resolved
 * registry no longer contains `includes` keys.
 *
 * @param {ExtensionRegistry} registry Raw extension registry.
 * @returns {ExtensionRegistry} Registry with includes resolved.
 */
function resolveIncludes(registry) {
  /** @type {ExtensionRegistry} */
  const resolved = {};

  for (const [name, entry] of Object.entries(registry)) {
    if (!entry.includes || entry.includes.length === 0) {
      resolved[name] = entry;
      continue;
    }

    /** @type {ExtensionEntry} */
    const merged = {...entry};
    delete merged.includes;

    for (const ref of entry.includes) {
      const target = registry[ref];
      if (!target) {
        throw new Error(`Extension ${name} includes unknown extension ${ref}`);
      }
      for (const key of /** @type {const} */ ([
        'typeNames',
        'variableNames',
        'constantNames',
        'functionNames',
        'typeKeywords',
        'storageQualifiers',
        'precisionQualifiers',
        'interpolationQualifiers',
        'attributes',
      ])) {
        if (target[key]) {
          merged[key] = [...(merged[key] || []), ...target[key]];
        }
      }
      if (target.definedMacros) {
        merged.definedMacros = {
          ...(merged.definedMacros || {}),
          ...target.definedMacros,
        };
      }
    }

    resolved[name] = merged;
  }

  return resolved;
}

export default resolveIncludes(EXTENSIONS);
