; This file is generated by generate_highlights.js.
; Edit queries/highlights.in or builtin.js, then regenerate.

"break" @keyword
"case" @keyword
"const" @keyword
"continue" @keyword
"default" @keyword
"discard" @keyword
"do" @keyword
"else" @keyword
"for" @keyword
"if" @keyword
"return" @keyword
"struct" @keyword
"switch" @keyword
"while" @keyword

(preproc_call
  directive: (preproc_directive) @keyword)

"=" @operator
(assignment_expression
  operator: _ @operator)

(binary_expression
  operator: _ @operator)

(unary_expression
  operator: _ @operator)

(update_expression
  operator: _ @operator)


"." @delimiter
"," @delimiter
";" @delimiter
"(" @delimiter
")" @delimiter
"[" @delimiter
"]" @delimiter
"{" @delimiter
"}" @delimiter

[
  (number_literal)
] @number

(bool_literal) @boolean

(comment) @comment

(invariant_qualifier) @keyword
(layout_qualifier) @keyword
(precise_qualifier) @keyword

((storage_qualifier) @keyword
 (#match? @keyword "^subroutine(\\(|$)"))

(function_declarator
  name: (identifier) @function)

(function_call
  function: (identifier) @function)

(function_call
  function: (field_expression
    field: (field_identifier) @function))

(preproc_function_def
  name: (identifier) @function.special)

(field_identifier) @property

(type_specifier
  (type_identifier) @type)

[
  "atomic_uint" "bool" "bvec2" "bvec3" "bvec4" "float" "iimage2D" "iimage2DArray"
  "iimage3D" "iimageBuffer" "iimageCube" "iimageCubeArray" "image2D" "image2DArray"
  "image3D" "imageBuffer" "imageCube" "imageCubeArray" "int" "isampler2D"
  "isampler2DArray" "isampler2DMS" "isampler2DMSArray" "isampler3D" "isamplerBuffer"
  "isamplerCube" "isamplerCubeArray" "ivec2" "ivec3" "ivec4" "mat2" "mat2x2" "mat2x3"
  "mat2x4" "mat3" "mat3x2" "mat3x3" "mat3x4" "mat4" "mat4x2" "mat4x3" "mat4x4"
  "sampler2D" "sampler2DArray" "sampler2DArrayShadow" "sampler2DMS" "sampler2DMSArray"
  "sampler2DShadow" "sampler3D" "samplerBuffer" "samplerCube" "samplerCubeArray"
  "samplerCubeArrayShadow" "samplerCubeShadow" "uimage2D" "uimage2DArray" "uimage3D"
  "uimageBuffer" "uimageCube" "uimageCubeArray" "uint" "usampler2D" "usampler2DArray"
  "usampler2DMS" "usampler2DMSArray" "usampler3D" "usamplerBuffer" "usamplerCube"
  "usamplerCubeArray" "uvec2" "uvec3" "uvec4" "vec2" "vec3" "vec4" "void" "dmat2"
  "dmat2x2" "dmat2x3" "dmat2x4" "dmat3" "dmat3x2" "dmat3x3" "dmat3x4" "dmat4" "dmat4x2"
  "dmat4x3" "dmat4x4" "double" "dvec2" "dvec3" "dvec4" "iimage1D" "iimage1DArray"
  "iimage2DMS" "iimage2DMSArray" "iimage2DRect" "image1D" "image1DArray" "image2DMS"
  "image2DMSArray" "image2DRect" "isampler1D" "isampler1DArray" "isampler2DRect"
  "itexture2DRect" "sampler1D" "sampler1DArray" "sampler1DArrayShadow" "sampler1DShadow"
  "sampler2DRect" "sampler2DRectShadow" "texture2DRect" "uimage1D" "uimage1DArray"
  "uimage2DMS" "uimage2DMSArray" "uimage2DRect" "usampler1D" "usampler1DArray"
  "usampler2DRect" "utexture2DRect" "isubpassInput" "isubpassInputMS" "itexture1D"
  "itexture1DArray" "itexture2D" "itexture2DArray" "itexture2DMS" "itexture2DMSArray"
  "itexture3D" "itextureBuffer" "itextureCube" "itextureCubeArray" "sampler"
  "samplerShadow" "subpassInput" "subpassInputMS" "texture1D" "texture1DArray"
  "texture2D" "texture2DArray" "texture2DMS" "texture2DMSArray" "texture3D"
  "textureBuffer" "textureCube" "textureCubeArray" "usubpassInput" "usubpassInputMS"
  "utexture1D" "utexture1DArray" "utexture2D" "utexture2DArray" "utexture2DMS"
  "utexture2DMSArray" "utexture3D" "utextureBuffer" "utextureCube" "utextureCubeArray"
  "tensorARM" "bf16vec2" "bf16vec3" "bf16vec4" "bfloat16_t" "fe4m3vec2" "fe4m3vec3"
  "fe4m3vec4" "floate4m3_t" "fe5m2vec2" "fe5m2vec3" "fe5m2vec4" "floate5m2_t" "f16mat2"
  "f16mat2x2" "f16mat2x3" "f16mat2x4" "f16mat3" "f16mat3x2" "f16mat3x3" "f16mat3x4"
  "f16mat4" "f16mat4x2" "f16mat4x3" "f16mat4x4" "f16vec2" "f16vec3" "f16vec4" "f32mat2"
  "f32mat2x2" "f32mat2x3" "f32mat2x4" "f32mat3" "f32mat3x2" "f32mat3x3" "f32mat3x4"
  "f32mat4" "f32mat4x2" "f32mat4x3" "f32mat4x4" "f32vec2" "f32vec3" "f32vec4" "f64mat2"
  "f64mat2x2" "f64mat2x3" "f64mat2x4" "f64mat3" "f64mat3x2" "f64mat3x3" "f64mat3x4"
  "f64mat4" "f64mat4x2" "f64mat4x3" "f64mat4x4" "f64vec2" "f64vec3" "f64vec4"
  "float16_t" "float32_t" "float64_t" "i16vec2" "i16vec3" "i16vec4" "i32vec2" "i32vec3"
  "i32vec4" "i64vec2" "i64vec3" "i64vec4" "i8vec2" "i8vec3" "i8vec4" "int16_t" "int32_t"
  "int64_t" "int8_t" "u16vec2" "u16vec3" "u16vec4" "u32vec2" "u32vec3" "u32vec4"
  "u64vec2" "u64vec3" "u64vec4" "u8vec2" "u8vec3" "u8vec4" "uint16_t" "uint32_t"
  "uint64_t" "uint8_t" "accelerationStructureEXT" "rayQueryEXT" "hitObjectEXT"
  "attachmentEXT" "iattachmentEXT" "uattachmentEXT" "coopmat" "coopmatNV" "fcoopmatNV"
  "icoopmatNV" "ucoopmatNV" "tensorLayoutNV" "tensorViewNV" "coopvecNV"
  "accelerationStructureNV" "hitObjectNV"
] @type.builtin

[
  "attribute" "buffer" "centroid" "coherent" "in" "inout" "out" "patch" "readonly"
  "restrict" "sample" "shared" "uniform" "varying" "volatile" "writeonly" "highp" "lowp"
  "mediump" "flat" "noperspective" "smooth" "nonuniformEXT" "subgroupuniformEXT"
  "pervertexEXT" "perprimitiveEXT" "taskPayloadSharedEXT" "nontemporal"
  "callableDataEXT" "callableDataInEXT" "hitAttributeEXT" "rayPayloadEXT"
  "rayPayloadInEXT" "shaderRecordEXT" "shadercallcoherent" "hitObjectAttributeEXT"
  "tileImageEXT" "pervertexNV" "perprimitiveNV" "perviewNV" "taskNV" "callableDataInNV"
  "callableDataNV" "hitAttributeNV" "rayPayloadInNV" "rayPayloadNV" "shaderRecordNV"
  "hitObjectAttributeNV"
] @type.qualifier

(layout_argument
  "shared" @attribute)

((layout_argument
   (identifier) @attribute)
 (#any-of? @attribute
  "lines" "local_size_x" "local_size_x_id" "local_size_y" "local_size_y_id"
  "local_size_z" "local_size_z_id" "max_primitives" "max_vertices" "points" "triangles"
  "branch" "dependency_infinite" "dependency_length" "dont_flatten" "dont_unroll"
  "flatten" "loop" "unroll" "iteration_multiple" "max_iterations" "min_iterations"
  "partial_count" "peel_count" "maximally_reconverges" "scalar"
  "subgroup_uniform_control_flow" "constant_id" "input_attachment_index" "push_constant"
  "set" "buffer_reference" "buffer_reference_align" "descriptor_heap"
  "descriptor_stride" "primitive_culling" "hitobjectshaderrecordext"
  "non_coherent_color_attachment_readEXT" "non_coherent_depth_attachment_readEXT"
  "non_coherent_stencil_attachment_readEXT" "derivative_group_linearNV"
  "derivative_group_quadsNV" "bank" "member_offset" "hitobjectshaderrecordnv")
)

((identifier) @constant
 (#match? @constant "^[A-Z][A-Z\\d_]*$"))

; Built-in constant names from builtins.adoc.
((identifier) @constant.builtin
 (#any-of? @constant.builtin
  "gl_ClusterIDNoneNV" "gl_ComponentTypeFloat16NV" "gl_ComponentTypeFloat32NV"
  "gl_ComponentTypeFloat64NV" "gl_ComponentTypeFloatE4M3NV"
  "gl_ComponentTypeFloatE5M2NV" "gl_ComponentTypeSignedInt16NV"
  "gl_ComponentTypeSignedInt32NV" "gl_ComponentTypeSignedInt64NV"
  "gl_ComponentTypeSignedInt8NV" "gl_ComponentTypeSignedInt8PackedNV"
  "gl_ComponentTypeUnsignedInt16NV" "gl_ComponentTypeUnsignedInt32NV"
  "gl_ComponentTypeUnsignedInt64NV" "gl_ComponentTypeUnsignedInt8NV"
  "gl_ComponentTypeUnsignedInt8PackedNV" "gl_CooperativeMatrixClampModeClampToEdgeNV"
  "gl_CooperativeMatrixClampModeConstantNV"
  "gl_CooperativeMatrixClampModeMirrorRepeatNV" "gl_CooperativeMatrixClampModeRepeatNV"
  "gl_CooperativeMatrixClampModeUndefinedNV"
  "gl_CooperativeMatrixLayoutColumnBlockedInterleavedARM"
  "gl_CooperativeMatrixLayoutColumnMajor"
  "gl_CooperativeMatrixLayoutRowBlockedInterleavedARM"
  "gl_CooperativeMatrixLayoutRowMajor" "gl_CooperativeMatrixReduce2x2NV"
  "gl_CooperativeMatrixReduceColumnNV" "gl_CooperativeMatrixReduceRowAndColumnNV"
  "gl_CooperativeMatrixReduceRowNV" "gl_CooperativeVectorMatrixLayoutColumnMajorNV"
  "gl_CooperativeVectorMatrixLayoutInferencingOptimalNV"
  "gl_CooperativeVectorMatrixLayoutRowMajorNV"
  "gl_CooperativeVectorMatrixLayoutTrainingOptimalNV" "gl_HitKindBackFacingTriangleEXT"
  "gl_HitKindFrontFacingTriangleEXT" "gl_MatrixOperandsSaturatingAccumulation"
  "gl_MatrixUseA" "gl_MatrixUseAccumulator" "gl_MatrixUseB"
  "gl_MaxAtomicCounterBindings" "gl_MaxAtomicCounterBufferSize" "gl_MaxClipDistances"
  "gl_MaxClipPlanes" "gl_MaxCombinedAtomicCounterBuffers" "gl_MaxCombinedAtomicCounters"
  "gl_MaxCombinedClipAndCullDistances" "gl_MaxCombinedImageUniforms"
  "gl_MaxCombinedImageUnitsAndFragmentOutputs" "gl_MaxCombinedShaderOutputResources"
  "gl_MaxCombinedTextureImageUnits" "gl_MaxComputeAtomicCounterBuffers"
  "gl_MaxComputeAtomicCounters" "gl_MaxComputeImageUniforms"
  "gl_MaxComputeTextureImageUnits" "gl_MaxComputeUniformComponents"
  "gl_MaxComputeWorkGroupCount" "gl_MaxComputeWorkGroupSize" "gl_MaxCullDistances"
  "gl_MaxDrawBuffers" "gl_MaxFragmentAtomicCounterBuffers"
  "gl_MaxFragmentAtomicCounters" "gl_MaxFragmentImageUniforms"
  "gl_MaxFragmentInputComponents" "gl_MaxFragmentInputVectors"
  "gl_MaxFragmentUniformComponents" "gl_MaxFragmentUniformVectors"
  "gl_MaxGeometryAtomicCounterBuffers" "gl_MaxGeometryAtomicCounters"
  "gl_MaxGeometryImageUniforms" "gl_MaxGeometryInputComponents"
  "gl_MaxGeometryOutputComponents" "gl_MaxGeometryOutputVertices"
  "gl_MaxGeometryTextureImageUnits" "gl_MaxGeometryTotalOutputComponents"
  "gl_MaxGeometryUniformComponents" "gl_MaxGeometryVaryingComponents"
  "gl_MaxImageSamples" "gl_MaxImageUnits" "gl_MaxInputAttachments" "gl_MaxLights"
  "gl_MaxMeshViewCountNV" "gl_MaxPatchVertices" "gl_MaxProgramTexelOffset"
  "gl_MaxSamples" "gl_MaxTessControlAtomicCounterBuffers"
  "gl_MaxTessControlAtomicCounters" "gl_MaxTessControlImageUniforms"
  "gl_MaxTessControlInputComponents" "gl_MaxTessControlOutputComponents"
  "gl_MaxTessControlTextureImageUnits" "gl_MaxTessControlTotalOutputComponents"
  "gl_MaxTessControlUniformComponents" "gl_MaxTessEvaluationAtomicCounterBuffers"
  "gl_MaxTessEvaluationAtomicCounters" "gl_MaxTessEvaluationImageUniforms"
  "gl_MaxTessEvaluationInputComponents" "gl_MaxTessEvaluationOutputComponents"
  "gl_MaxTessEvaluationTextureImageUnits" "gl_MaxTessEvaluationUniformComponents"
  "gl_MaxTessGenLevel" "gl_MaxTessPatchComponents" "gl_MaxTextureCoords"
  "gl_MaxTextureImageUnits" "gl_MaxTextureUnits" "gl_MaxTransformFeedbackBuffers"
  "gl_MaxTransformFeedbackInterleavedComponents" "gl_MaxVaryingComponents"
  "gl_MaxVaryingFloats" "gl_MaxVaryingVectors" "gl_MaxVertexAtomicCounterBuffers"
  "gl_MaxVertexAtomicCounters" "gl_MaxVertexAttribs" "gl_MaxVertexImageUniforms"
  "gl_MaxVertexOutputComponents" "gl_MaxVertexOutputVectors"
  "gl_MaxVertexTextureImageUnits" "gl_MaxVertexUniformComponents"
  "gl_MaxVertexUniformVectors" "gl_MaxViewports" "gl_MinProgramTexelOffset"
  "gl_RayFlagsCullBackFacingTrianglesEXT" "gl_RayFlagsCullBackFacingTrianglesNV"
  "gl_RayFlagsCullFrontFacingTrianglesEXT" "gl_RayFlagsCullFrontFacingTrianglesNV"
  "gl_RayFlagsCullNoOpaqueEXT" "gl_RayFlagsCullNoOpaqueNV" "gl_RayFlagsCullOpaqueEXT"
  "gl_RayFlagsCullOpaqueNV" "gl_RayFlagsForceOpacityMicromap2StateEXT"
  "gl_RayFlagsNoneEXT" "gl_RayFlagsNoneNV" "gl_RayFlagsNoOpaqueEXT"
  "gl_RayFlagsNoOpaqueNV" "gl_RayFlagsOpaqueEXT" "gl_RayFlagsOpaqueNV"
  "gl_RayFlagsSkipAABBEXT" "gl_RayFlagsSkipBuiltinPrimitivesNV"
  "gl_RayFlagsSkipClosestHitShaderEXT" "gl_RayFlagsSkipClosestHitShaderNV"
  "gl_RayFlagsSkipTrianglesEXT" "gl_RayFlagsTerminateOnFirstHitEXT"
  "gl_RayFlagsTerminateOnFirstHitNV" "gl_RayQueryCandidateIntersectionAABBEXT"
  "gl_RayQueryCandidateIntersectionTriangleEXT"
  "gl_RayQueryCommittedIntersectionGeneratedEXT"
  "gl_RayQueryCommittedIntersectionNoneEXT"
  "gl_RayQueryCommittedIntersectionTriangleEXT" "gl_ScopeDevice" "gl_ScopeInvocation"
  "gl_ScopeQueueFamily" "gl_ScopeShaderCallEXT" "gl_ScopeSubgroup" "gl_ScopeWorkgroup"
  "gl_SemanticsAcquire" "gl_SemanticsAcquireRelease" "gl_SemanticsMakeAvailable"
  "gl_SemanticsMakeVisible" "gl_SemanticsRelaxed" "gl_SemanticsRelease"
  "gl_SemanticsVolatile" "gl_ShadingRateFlag2HorizontalPixelsEXT"
  "gl_ShadingRateFlag2VerticalPixelsEXT" "gl_ShadingRateFlag4HorizontalPixelsEXT"
  "gl_ShadingRateFlag4VerticalPixelsEXT" "gl_StorageSemanticsBuffer"
  "gl_StorageSemanticsImage" "gl_StorageSemanticsNone" "gl_StorageSemanticsOutput"
  "gl_StorageSemanticsShared" "gl_TensorOperandsNonTemporalARM"
  "gl_TensorOperandsOutOfBoundsValueARM" "gl_WorkGroupSize"))

; Built-in variable names from builtins.adoc.
((identifier) @variable.builtin
 (#any-of? @variable.builtin
  "gl_BackColor" "gl_BackLightModelProduct" "gl_BackLightProduct" "gl_BackMaterial"
  "gl_BackSecondaryColor" "gl_BaryCoordEXT" "gl_BaryCoordNoPerspAMD"
  "gl_BaryCoordNoPerspCentroidAMD" "gl_BaryCoordNoPerspEXT" "gl_BaryCoordNoPerspNV"
  "gl_BaryCoordNoPerspSampleAMD" "gl_BaryCoordNV" "gl_BaryCoordPullModelAMD"
  "gl_BaryCoordSmoothAMD" "gl_BaryCoordSmoothCentroidAMD" "gl_BaryCoordSmoothSampleAMD"
  "gl_BaseInstance" "gl_BaseVertex" "gl_BoundingBox" "gl_ClipDistance"
  "gl_ClipDistancePerViewEXT" "gl_ClipDistancePerViewNV" "gl_ClipPlane" "gl_ClipVertex"
  "gl_ClusterIDHUAWEI" "gl_ClusterIDNV" "gl_Color" "gl_CoreCountARM" "gl_CoreIDARM"
  "gl_CoreMaxIDARM" "gl_CullDistance" "gl_CullDistancePerViewEXT"
  "gl_CullDistancePerViewNV" "gl_CullMaskEXT" "gl_CullPrimitiveEXT"
  "gl_CurrentRayTimeNV" "gl_DepthRange" "gl_DeviceIndex" "gl_DrawID" "gl_EyePlaneQ"
  "gl_EyePlaneR" "gl_EyePlaneS" "gl_EyePlaneT" "gl_FirstIndexHUAWEI"
  "gl_FirstInstanceHUAWEI" "gl_FirstVertexHUAWEI" "gl_Fog" "gl_FogCoord"
  "gl_FogFragCoord" "gl_FragColor" "gl_FragCoord" "gl_FragData" "gl_FragDepth"
  "gl_FragInvocationCountEXT" "gl_FragmentSizeNV" "gl_FragSizeEXT" "gl_FragSizeNV"
  "gl_FragStencilRefARB" "gl_FrontColor" "gl_FrontFacing" "gl_FrontLightModelProduct"
  "gl_FrontLightProduct" "gl_FrontMaterial" "gl_FrontSecondaryColor"
  "gl_GeometryIndexEXT" "gl_GlobalInvocationID" "gl_HelperInvocation"
  "gl_HelperThreadNV" "gl_HitIsLSSNV" "gl_HitIsSphereNV"
  "gl_HitKindBackFacingMicroTriangleNV" "gl_HitKindEXT"
  "gl_HitKindFrontFacingMicroTriangleNV" "gl_HitKindNV" "gl_HitLSSPositionsNV"
  "gl_HitLSSRadiiNV" "gl_HitMicroTriangleVertexBarycentricsNV"
  "gl_HitMicroTriangleVertexPositionsNV" "gl_HitSpherePositionNV" "gl_HitSphereRadiusNV"
  "gl_HitTEXT" "gl_HitTNV" "gl_HitTriangleVertexPositionsEXT" "gl_in"
  "gl_IncomingRayFlagsEXT" "gl_IncomingRayFlagsNV" "gl_IndexCountHUAWEI"
  "gl_InstanceCountHUAWEI" "gl_InstanceCustomIndexEXT" "gl_InstanceCustomIndexNV"
  "gl_InstanceID" "gl_InstanceIndex" "gl_InvocationID" "gl_InvocationsPerPixelNV"
  "gl_LaunchIDEXT" "gl_LaunchIDNV" "gl_LaunchSizeEXT" "gl_LaunchSizeNV" "gl_Layer"
  "gl_LayerPerViewNV" "gl_LightModel" "gl_LightSource" "gl_LocalInvocationID"
  "gl_LocalInvocationIndex" "gl_MeshPrimitivesEXT" "gl_MeshPrimitivesNV"
  "gl_MeshVerticesEXT" "gl_MeshVerticesNV" "gl_MeshViewCountNV" "gl_MeshViewIndicesNV"
  "gl_ModelViewMatrix" "gl_ModelViewMatrixInverse" "gl_ModelViewMatrixInverseTranspose"
  "gl_ModelViewMatrixTranspose" "gl_ModelViewProjectionMatrix"
  "gl_ModelViewProjectionMatrixInverse" "gl_ModelViewProjectionMatrixInverseTranspose"
  "gl_ModelViewProjectionMatrixTranspose" "gl_MultiTexCoord0" "gl_MultiTexCoord1"
  "gl_MultiTexCoord2" "gl_MultiTexCoord3" "gl_MultiTexCoord4" "gl_MultiTexCoord5"
  "gl_MultiTexCoord6" "gl_MultiTexCoord7" "gl_Normal" "gl_NormalMatrix" "gl_NormalScale"
  "gl_NumSamples" "gl_NumSubgroups" "gl_NumWorkGroups" "gl_ObjectPlaneQ"
  "gl_ObjectPlaneR" "gl_ObjectPlaneS" "gl_ObjectPlaneT" "gl_ObjectRayDirectionEXT"
  "gl_ObjectRayDirectionNV" "gl_ObjectRayOriginEXT" "gl_ObjectRayOriginNV"
  "gl_ObjectToWorld3x4EXT" "gl_ObjectToWorldEXT" "gl_ObjectToWorldNV" "gl_out"
  "gl_PatchVerticesIn" "gl_Point" "gl_PointCoord" "gl_PointSize" "gl_Position"
  "gl_PositionPerViewNV" "gl_PrimitiveCountNV" "gl_PrimitiveID" "gl_PrimitiveIDIn"
  "gl_PrimitiveIndicesNV" "gl_PrimitiveLineIndicesEXT" "gl_PrimitivePointIndicesEXT"
  "gl_PrimitiveShadingRateEXT" "gl_PrimitiveTriangleIndicesEXT" "gl_ProjectionMatrix"
  "gl_ProjectionMatrixInverse" "gl_ProjectionMatrixInverseTranspose"
  "gl_ProjectionMatrixTranspose" "gl_RayFlagsEXT" "gl_RayTmaxEXT" "gl_RayTMaxEXT"
  "gl_RayTmaxNV" "gl_RayTminEXT" "gl_RayTMinEXT" "gl_RayTminNV" "gl_SampleID"
  "gl_SampleMask" "gl_SampleMaskIn" "gl_SamplePosition" "gl_SecondaryColor"
  "gl_ShadingRateEXT" "gl_ShadingRateNV" "gl_ShadingRatePerViewNV" "gl_SMCountNV"
  "gl_SMIDNV" "gl_SubgroupEqMask" "gl_SubgroupGeMask" "gl_SubgroupGtMask"
  "gl_SubgroupID" "gl_SubgroupInvocationID" "gl_SubgroupLeMask" "gl_SubgroupLtMask"
  "gl_SubgroupSize" "gl_TaskCountNV" "gl_TessCoord" "gl_TessLevelInner"
  "gl_TessLevelOuter" "gl_TexCoord" "gl_TextureEnvColor" "gl_TextureMatrix"
  "gl_TextureMatrixInverse" "gl_TextureMatrixInverseTranspose"
  "gl_TextureMatrixTranspose" "gl_ThreadInWarpNV" "gl_TileApronSizeQCOM"
  "gl_TileDimensionQCOM" "gl_TileOffsetQCOM" "gl_Vertex" "gl_VertexCountHUAWEI"
  "gl_VertexID" "gl_VertexIndex" "gl_VertexOffsetHUAWEI" "gl_ViewIndex"
  "gl_ViewportIndex" "gl_ViewportMaskPerViewNV" "gl_WarpIDARM" "gl_WarpIDNV"
  "gl_WarpMaxIDARM" "gl_WarpSizeNV" "gl_WarpsPerSMNV" "gl_WorkGroupID"
  "gl_WorldRayDirectionEXT" "gl_WorldRayDirectionNV" "gl_WorldRayOriginEXT"
  "gl_WorldRayOriginNV" "gl_WorldToObject3x4EXT" "gl_WorldToObjectEXT"
  "gl_WorldToObjectNV"))

; Built-in type-like names from builtins.adoc such as gl_PerVertex.
((type_specifier
   (type_identifier) @type.builtin)
 (#any-of? @type.builtin
  "__explicitInterpAMD" "accelerationStructureEXT" "accelerationStructureNV"
  "attachmentEXT" "callableDataEXT" "callableDataInEXT" "coopmatNV" "coopvecNV"
  "derivative_group_linearNV" "derivative_group_quadsNV" "fcoopmatNV"
  "gl_DepthRangeParameters" "gl_FogParameters" "gl_LightModelParameters"
  "gl_LightModelProducts" "gl_LightProducts" "gl_LightSourceParameters"
  "gl_MaterialParameters" "gl_MeshPerPrimitiveEXT" "gl_MeshPerPrimitiveNV"
  "gl_MeshPerVertexEXT" "gl_MeshPerVertexNV" "gl_PerClusterHUAWEI" "gl_PerFragment"
  "gl_PerVertex" "gl_PointParameters" "gl_TextureFootprint2DNV"
  "gl_TextureFootprint3DNV" "hitAttributeEXT" "hitObjectEXT" "hitObjectNV"
  "iattachmentEXT" "icoopmatNV" "non_coherent_attachment_readQCOM" "nonuniformEXT"
  "perprimitiveEXT" "pervertexEXT" "pervertexNV" "rayPayloadEXT" "rayPayloadInEXT"
  "rayQueryEXT" "shaderRecordEXT" "shaderRecordNV" "shading_rate_xQCOM"
  "shading_rate_yQCOM" "shading_rate_zQCOM" "subgroupPartitionNV" "subgroupuniformEXT"
  "taskPayloadSharedEXT" "tensorARM" "tensorLayoutNV" "tensorViewNV"
  "tile_attachmentQCOM" "uattachmentEXT" "ucoopmatNV"))

; Built-in function names from builtinfunctions.adoc.
; Vulkan-only built-in function names from builtinfunctions.adoc.
((function_call
   function: (identifier) @function.builtin.vk)
 (#any-of? @function.builtin.vk
  "subpassLoad"))

; Built-in function names from builtinfunctions.adoc.
((function_call
   function: (identifier) @function.builtin)
 (#any-of? @function.builtin
  "abs" "acos" "acosh" "activeThreadsNV" "all" "allInvocations" "allInvocationsEqual"
  "any" "anyInvocation" "asin" "asinh" "assumeEXT" "atan" "atanh" "atomicAdd"
  "atomicAnd" "atomicCompSwap" "atomicCounter" "atomicCounterAdd" "atomicCounterAnd"
  "atomicCounterCompSwap" "atomicCounterDecrement" "atomicCounterExchange"
  "atomicCounterIncrement" "atomicCounterMax" "atomicCounterMin" "atomicCounterOr"
  "atomicCounterSubtract" "atomicCounterXor" "atomicExchange" "atomicLoad" "atomicMax"
  "atomicMin" "atomicOr" "atomicStore" "atomicXor" "ballotThreadNV" "barrier"
  "bfloat16BitsToIntEXT" "bfloat16BitsToUintEXT" "bitcastQCOM" "bitCount"
  "bitfieldExtract" "bitfieldInsert" "bitfieldReverse" "ceil" "clamp"
  "clockRealtime2x32EXT" "clockRealtimeEXT" "colorAttachmentReadEXT"
  "ComputeAccessedLod" "controlBarrier" "coopMatLoad" "coopMatLoadNV"
  "coopMatLoadTensorNV" "coopMatMulAdd" "coopMatMulAddNV" "coopMatPerElementNV"
  "coopMatReduceNV" "coopMatStore" "coopMatStoreNV" "coopMatStoreTensorNV"
  "coopmatToVectorQCOM" "coopMatTransposeNV" "coopVecLoadNV" "coopVecMatMulAddNV"
  "coopVecMatMulNV" "coopVecOuterProductAccumulateNV" "coopVecReduceSumAccumulateNV"
  "coopVecStoreNV" "cos" "cosh" "createTensorLayoutNV" "createTensorViewNV" "cross"
  "debugPrintfEXT" "degrees" "depthAttachmentReadEXT" "determinant" "dFdx" "dFdxCoarse"
  "dFdxFine" "dFdy" "dFdyCoarse" "dFdyFine" "distance" "dot" "dotAccSatEXT" "dotEXT"
  "dotPacked4x8AccSatEXT" "dotPacked4x8EXT" "doubleBitsToInt64" "doubleBitsToUint64"
  "EmitMeshTasksEXT" "EmitStreamVertex" "EmitVertex" "EndPrimitive" "EndStreamPrimitive"
  "equal" "executeCallableEXT" "executeCallableNV" "exp" "exp2" "expectEXT"
  "extractSubArrayQCOM" "faceforward" "fetchMicroTriangleVertexBarycentricNV"
  "fetchMicroTriangleVertexPositionNV" "findLSB" "findMSB" "float16BitsToInt16"
  "float16BitsToUint16" "floatBitsToInt" "floatBitsToUint" "floate4m3BitsToIntEXT"
  "floate4m3BitsToUintEXT" "floate5m2BitsToIntEXT" "floate5m2BitsToUintEXT" "floor"
  "fma" "fract" "fragmentFetchAMD" "fragmentMaskFetchAMD" "frexp" "ftransform" "fwidth"
  "fwidthCoarse" "fwidthFine" "greaterThan" "greaterThanEqual" "groupMemoryBarrier"
  "halfBitsToInt16" "halfBitsToUint16" "helperInvocationEXT" "hitObjectExecuteShaderEXT"
  "hitObjectExecuteShaderNV" "hitObjectGetAttributesEXT" "hitObjectGetAttributesNV"
  "hitObjectGetClusterIdNV" "hitObjectGetCurrentTimeEXT" "hitObjectGetCurrentTimeNV"
  "hitObjectGetGeometryIndexEXT" "hitObjectGetGeometryIndexNV" "hitObjectGetHitKindEXT"
  "hitObjectGetHitKindNV" "hitObjectGetInstanceCustomIndexEXT"
  "hitObjectGetInstanceCustomIndexNV" "hitObjectGetInstanceIdEXT"
  "hitObjectGetInstanceIdNV" "hitObjectGetIntersectionTriangleVertexPositionsEXT"
  "hitObjectGetLSSPositionsNV" "hitObjectGetLSSRadiiNV"
  "hitObjectGetObjectRayDirectionEXT" "hitObjectGetObjectRayDirectionNV"
  "hitObjectGetObjectRayOriginEXT" "hitObjectGetObjectRayOriginNV"
  "hitObjectGetObjectToWorldEXT" "hitObjectGetObjectToWorldNV"
  "hitObjectGetPrimitiveIndexEXT" "hitObjectGetPrimitiveIndexNV"
  "hitObjectGetRayFlagsEXT" "hitObjectGetRayTMaxEXT" "hitObjectGetRayTMaxNV"
  "hitObjectGetRayTMinEXT" "hitObjectGetRayTMinNV"
  "hitObjectGetShaderBindingTableRecordIndexEXT"
  "hitObjectGetShaderBindingTableRecordIndexNV"
  "hitObjectGetShaderRecordBufferHandleEXT" "hitObjectGetShaderRecordBufferHandleNV"
  "hitObjectGetSpherePositionNV" "hitObjectGetSphereRadiusNV"
  "hitObjectGetWorldRayDirectionEXT" "hitObjectGetWorldRayDirectionNV"
  "hitObjectGetWorldRayOriginEXT" "hitObjectGetWorldRayOriginNV"
  "hitObjectGetWorldToObjectEXT" "hitObjectGetWorldToObjectNV" "hitObjectIsEmptyEXT"
  "hitObjectIsEmptyNV" "hitObjectIsHitEXT" "hitObjectIsHitNV" "hitObjectIsMissEXT"
  "hitObjectIsMissNV" "hitObjectRecordEmptyEXT" "hitObjectRecordEmptyNV"
  "hitObjectRecordFromQueryEXT" "hitObjectRecordHitMotionNV" "hitObjectRecordHitNV"
  "hitObjectRecordHitWithIndexMotionNV" "hitObjectRecordHitWithIndexNV"
  "hitObjectRecordMissEXT" "hitObjectRecordMissMotionEXT" "hitObjectRecordMissMotionNV"
  "hitObjectRecordMissNV" "hitObjectReorderExecuteEXT"
  "hitObjectSetShaderBindingTableRecordIndexEXT" "hitObjectTraceMotionReorderExecuteEXT"
  "hitObjectTraceRayEXT" "hitObjectTraceRayMotionEXT" "hitObjectTraceRayMotionNV"
  "hitObjectTraceRayNV" "hitObjectTraceReorderExecuteEXT" "ignoreIntersectionEXT"
  "ignoreIntersectionNV" "imageAtomicAdd" "imageAtomicAnd" "imageAtomicCompSwap"
  "imageAtomicExchange" "imageAtomicLoad" "imageAtomicMax" "imageAtomicMin"
  "imageAtomicOr" "imageAtomicStore" "imageAtomicXor" "imageLoad" "imageSamples"
  "imageSize" "imageStore" "imulExtended" "int16BitsToFloat16" "int16BitsToHalf"
  "int64BitsToDouble" "intBitsToBFloat16EXT" "intBitsToFloat" "intBitsToFloate4m3EXT"
  "intBitsToFloate5m2EXT" "interpolateAtCentroid" "interpolateAtOffset"
  "interpolateAtSample" "interpolateAtVertexAMD" "inverse" "inversesqrt" "isinf" "isnan"
  "ldexp" "length" "length64" "lessThan" "lessThanEqual" "log" "log2" "matrixCompMult"
  "max" "max3" "memoryBarrier" "memoryBarrierAtomicCounter" "memoryBarrierBuffer"
  "memoryBarrierImage" "memoryBarrierShared" "mid3" "min" "min3" "mix" "mod" "modf"
  "noise1" "noise2" "noise3" "noise4" "normalize" "not" "notEqual" "outerProduct"
  "pack16" "pack32" "pack64" "packDouble2x32" "packFloat2x16" "packHalf2x16"
  "packInt2x16" "packInt2x32" "packInt4x16" "packSnorm2x16" "packSnorm4x8"
  "packUint2x16" "packUint2x32" "packUint4x16" "packUnorm2x16" "packUnorm4x8" "pow"
  "quadSwizzle0NV" "quadSwizzle1NV" "quadSwizzle2NV" "quadSwizzle3NV" "quadSwizzleXNV"
  "quadSwizzleYNV" "radians" "rayQueryConfirmIntersectionEXT"
  "rayQueryGenerateIntersectionEXT" "rayQueryGetIntersectionBarycentricsEXT"
  "rayQueryGetIntersectionCandidateAABBOpaqueEXT" "rayQueryGetIntersectionClusterIdNV"
  "rayQueryGetIntersectionFrontFaceEXT" "rayQueryGetIntersectionGeometryIndexEXT"
  "rayQueryGetIntersectionInstanceCustomIndexEXT" "rayQueryGetIntersectionInstanceIdEXT"
  "rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT"
  "rayQueryGetIntersectionLSSHitValueNV" "rayQueryGetIntersectionLSSPositionsNV"
  "rayQueryGetIntersectionLSSRadiiNV" "rayQueryGetIntersectionObjectRayDirectionEXT"
  "rayQueryGetIntersectionObjectRayOriginEXT" "rayQueryGetIntersectionObjectToWorldEXT"
  "rayQueryGetIntersectionPrimitiveIndexEXT" "rayQueryGetIntersectionSpherePositionNV"
  "rayQueryGetIntersectionSphereRadiusNV" "rayQueryGetIntersectionTEXT"
  "rayQueryGetIntersectionTriangleVertexPositionsEXT" "rayQueryGetIntersectionTypeEXT"
  "rayQueryGetIntersectionWorldToObjectEXT" "rayQueryGetRayFlagsEXT"
  "rayQueryGetRayTMinEXT" "rayQueryGetWorldRayDirectionEXT"
  "rayQueryGetWorldRayOriginEXT" "rayQueryInitializeEXT" "rayQueryIsLSSHitNV"
  "rayQueryIsSphereHitNV" "rayQueryProceedEXT" "rayQueryTerminateEXT" "reflect"
  "refract" "reorderThreadEXT" "reorderThreadNV" "reportIntersectionEXT"
  "reportIntersectionNV" "round" "roundEven" "saturatedConvertEXT" "SetMeshOutputsEXT"
  "setTensorLayoutBlockSizeNV" "setTensorLayoutClampValueNV"
  "setTensorLayoutDimensionNV" "setTensorLayoutStrideNV" "setTensorViewClipNV"
  "setTensorViewDimensionsNV" "setTensorViewStrideNV" "shadow1D" "shadow1DLod"
  "shadow1DProj" "shadow1DProjLod" "shadow2D" "shadow2DLod" "shadow2DProj"
  "shadow2DProjLod" "sign" "sin" "sinh" "sliceTensorLayoutNV" "smoothstep" "sqrt"
  "stencilAttachmentReadEXT" "step" "subgroupAdd" "subgroupAll" "subgroupAllEqual"
  "subgroupAnd" "subgroupAny" "subgroupBallot" "subgroupBallotBitCount"
  "subgroupBallotBitExtract" "subgroupBallotExclusiveBitCount" "subgroupBallotFindLSB"
  "subgroupBallotFindMSB" "subgroupBallotInclusiveBitCount" "subgroupBarrier"
  "subgroupBroadcast" "subgroupBroadcastFirst" "subgroupClusteredAdd"
  "subgroupClusteredAnd" "subgroupClusteredMax" "subgroupClusteredMin"
  "subgroupClusteredMul" "subgroupClusteredOr" "subgroupClusteredRotate"
  "subgroupClusteredXor" "subgroupElect" "subgroupExclusiveAdd" "subgroupExclusiveAnd"
  "subgroupExclusiveMax" "subgroupExclusiveMin" "subgroupExclusiveMul"
  "subgroupExclusiveOr" "subgroupExclusiveXor" "subgroupInclusiveAdd"
  "subgroupInclusiveAnd" "subgroupInclusiveMax" "subgroupInclusiveMin"
  "subgroupInclusiveMul" "subgroupInclusiveOr" "subgroupInclusiveXor"
  "subgroupInverseBallot" "subgroupMax" "subgroupMemoryBarrier"
  "subgroupMemoryBarrierBuffer" "subgroupMemoryBarrierImage"
  "subgroupMemoryBarrierShared" "subgroupMin" "subgroupMul" "subgroupOr"
  "subgroupPartitionedAddNV" "subgroupPartitionedAndNV"
  "subgroupPartitionedExclusiveAddNV" "subgroupPartitionedExclusiveAndNV"
  "subgroupPartitionedExclusiveMaxNV" "subgroupPartitionedExclusiveMinNV"
  "subgroupPartitionedExclusiveMulNV" "subgroupPartitionedExclusiveOrNV"
  "subgroupPartitionedExclusiveXorNV" "subgroupPartitionedInclusiveAddNV"
  "subgroupPartitionedInclusiveAndNV" "subgroupPartitionedInclusiveMaxNV"
  "subgroupPartitionedInclusiveMinNV" "subgroupPartitionedInclusiveMulNV"
  "subgroupPartitionedInclusiveOrNV" "subgroupPartitionedInclusiveXorNV"
  "subgroupPartitionedMaxNV" "subgroupPartitionedMinNV" "subgroupPartitionedMulNV"
  "subgroupPartitionedOrNV" "subgroupPartitionedXorNV" "subgroupPartitionNV"
  "subgroupQuadBroadcast" "subgroupQuadSwapDiagonal" "subgroupQuadSwapHorizontal"
  "subgroupQuadSwapVertical" "subgroupRotate" "subgroupShuffle" "subgroupShuffleDown"
  "subgroupShuffleUp" "subgroupShuffleXor" "subgroupXor" "tan" "tanh" "tensorReadARM"
  "tensorSizeARM" "tensorWriteARM" "terminateRayEXT" "terminateRayNV" "texelFetch"
  "texelFetchOffset" "texture" "texture1D" "texture1DLod" "texture1DProj"
  "texture1DProjLod" "texture2D" "texture2DLod" "texture2DProj" "texture2DProjLod"
  "texture3D" "texture3DLod" "texture3DProj" "texture3DProjLod"
  "textureBlockMatchGatherSADQCOM" "textureBlockMatchGatherSSDQCOM"
  "textureBlockMatchSADQCOM" "textureBlockMatchSSDQCOM" "textureBlockMatchWindowSADQCOM"
  "textureBlockMatchWindowSSDQCOM" "textureBoxFilterQCOM" "textureCube" "textureCubeLod"
  "textureFootprintClampNV" "textureFootprintGradClampNV" "textureFootprintGradNV"
  "textureFootprintLodNV" "textureFootprintNV" "textureGather" "textureGatherOffset"
  "textureGatherOffsets" "textureGrad" "textureGradOffset" "textureLod"
  "textureLodOffset" "textureOffset" "textureProj" "textureProjGrad"
  "textureProjGradOffset" "textureProjLod" "textureProjLodOffset" "textureProjOffset"
  "textureQueryLevels" "textureQueryLod" "textureSamples" "textureSize"
  "textureWeightedQCOM" "traceNV" "traceRayEXT" "traceRayMotionNV" "transpose" "trunc"
  "uaddCarry" "uint16BitsToFloat16" "uint16BitsToHalf" "uint64BitsToDouble"
  "uintBitsToBFloat16EXT" "uintBitsToFloat" "uintBitsToFloate4m3EXT"
  "uintBitsToFloate5m2EXT" "umulExtended" "unpack16" "unpack32" "unpack8"
  "unpackDouble2x32" "unpackFloat2x16" "unpackHalf2x16" "unpackInt2x16" "unpackInt2x32"
  "unpackInt4x16" "unpackSnorm2x16" "unpackSnorm4x8" "unpackUint2x16" "unpackUint2x32"
  "unpackUint4x16" "unpackUnorm2x16" "unpackUnorm4x8" "usubBorrow" "vectorToCoopmatQCOM"
  "writePackedPrimitiveIndices4x8NV"))

(identifier) @variable
