name: CI

on:
  push:
    branches: [master]
    paths:
  pull_request:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action@v1
        with:
          install-lib: false
      - uses: tree-sitter/parser-test-action@v1.2
        with:
          test-library: true
